### ISSUE TITLE
Passing in custom types as function parameters in Sway causes unexpected behaviour when testing in `harness.rs`

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/fuels-rs#296] opened 2022-05-15 13:08 UTC
I've been having trouble with running some tests and it _seems_ like it might have something to do with using custom types (structs / enums) as parameters in a sway contract. I do not know what the issue is as it is inconsistent and while trying to reproduce in the following minimal example I am getting a different error message.

The error message regarding this specific minimal implementation is
![1](https://user-images.githubusercontent.com/103777923/168473967-54093a32-3383-4296-9990-aa6720fbe4fc.png)

The minimal steps to reproduce the `fuels_core` error message is as follows.

1. `forc init testing_errors`
2. Copy and paste the code below into the `main.sw` and `harness.rs` files (save the files)
3. `forc test` (this should pass / not panic)
4. This time uncomment the `test_function(param: Person)` and comment out the alternative which takes no parameters
5. Save the `main.sw` file
6. There are two possible routes here
    - `forc test` (this should pass)
    - Alternatively to running `forc test` above first save the `harness.rs` (after step 5) and then `forc test` will panic

Note that the act of taking step 5 (saving the `main.sw`) and then saving the `harness.rs` file causes the panic despite no changes being made to the test file at any point.
Furthermore, the struct does not cause issues in the function body but it does cause an issue in the signature.
This issue does not illustrate the use of an enum however I have been having issues with the enums as well.

The following error message is the original error message that I've been getting in a different project - and actually across multiple projects. It always starts with the `abigen` macro failing.
Again, note that the "path" is not the issue since the tests are run and pass until this save is made in the test file.
![1](https://user-images.githubusercontent.com/103777923/168474363-339f5a00-73e2-42ce-831d-c3c1342b9a2a.png)

`main.rs`

```
contract;

struct Person {
    name: str[4]
}

abi MyContract {
    // fn test_function(param: Person) -> bool;
    fn test_function() -> bool;
}

impl MyContract for Contract {
    // fn test_function(param: Person) -> bool {
    //     true
    // }

    fn test_function() -> bool {
        let p = Person { name: "John" };
        true
    }
}
```

`harness.rs`

```
use fuel_tx::ContractId;
use fuels_abigen_macro::abigen;
use fuels::prelude::*;
use fuels::test_helpers;

// Load abi from json
abigen!(MyContract, "out/debug/testing_errors-abi.json");

struct Person {
    name: String
}

async fn get_contract_instance() -> (MyContract, ContractId) {
    // Deploy the compiled contract
    let compiled = Contract::load_sway_contract("./out/debug/testing_errors.bin").unwrap();

    // Launch a local network and deploy the contract
    let (provider, wallet) = test_helpers::setup_test_provider_and_wallet().await;

    let id = Contract::deploy(&compiled, &provider, &wallet, TxParameters::default())
        .await
        .unwrap();

    let instance = MyContract::new(id.to_string(), provider, wallet);

    (instance, id)
}

#[tokio::test]
async fn can_get_contract_id() {
    let (_instance, _id) = get_contract_instance().await;

    // Now you have an instance of your contract you can use to test each function
//    assert_eq!(true, _instance.test_function(Person { name: String::from("John") }).call().await.unwrap().value);
}
```

**Comment by adlerjohn** [comment] 2022-05-19 19:25
The unit type enum case has been resolve with #283, but looks like there's still another similar error. Potentially with arrays of structs with more than one `b256`?

**Comment by Braqzen** [comment] 2022-05-19 20:37
> The unit type enum case has been resolve with #283, but looks like there's still another similar error. Potentially with arrays of structs with more than one `b256`?

An array of `Address` fails too. That has a single `b256` field.
Generally structs seem to fail in arrays, also enums.
Moreover, a struct with just a single `u64` fails but again... only after you save the `harness.rs` file...

**Comment by digorithm** [comment] 2022-05-22 19:10
Can't repro most of the issues described here, _except_ in the case of arrays of structs, which I managed to reproduce and find where the problem is happening. I've documented it here https://github.com/FuelLabs/fuels-rs/issues/306 but it needs compiler support first, which I documented here https://github.com/FuelLabs/sway/issues/1631.

**Comment by mohammadfawaz** [comment] 2022-05-24 17:26
`forc 0.13.1` has the fix for https://github.com/FuelLabs/sway/issues/1631.

**Comment by Braqzen** [comment] 2022-05-24 18:30
> `forc 0.13.1` has the fix for [FuelLabs/sway#1631](https://github.com/FuelLabs/sway/issues/1631).
![1](https://user-images.githubusercontent.com/103777923/170106729-d052918b-7989-40c0-8c77-085b5f6a55af.png)

The ABI may be fixed however `forc test` still breaks with the same issue.
This specific error message has not been presented in the images above however it is one of the error messages that I have been getting.

**Comment by mohammadfawaz** [comment] 2022-05-24 18:33
Yeah probably expected! I think https://github.com/FuelLabs/fuels-rs/issues/306 has to be fixed and release before `forc test` passes.

**Comment by Braqzen** [comment] 2022-05-25 17:30
@emilyaherbert It seems like arrays of structs remain broken in the SDK. Passing in enums, structs and arrays containing enums (but not arrays containing structs) seems to not longer break the tests.
This issue can probably be closed since #306 addresses this specifically.

**Comment by mohammadfawaz** [comment] 2022-05-25 17:40
I will close the issue as all the required changes in the Sway repo have been made. https://github.com/FuelLabs/fuels-rs/issues/306 will handle the rest.

**Comment by mohammadfawaz** [comment] 2022-05-25 17:40
I will close the issue as all the required changes in the Sway repo have been made. https://github.com/FuelLabs/fuels-rs/issues/306 tracks the of the work.

**Closed by mohammadfawaz** 2022-05-25 17:40 UTC
Labels: bug, help wanted, P: critical, testing, blocked
