### ISSUE TITLE
Adding configurables breaks contracts | fuels v0.65.1, forc 0.61.2 / forc 0.62.0

### ISSUE THREAD

**Issue by DefiCake** [FuelLabs/fuels-rs#1475] opened 2024-08-01 10:12 UTC
Reproduction: https://github.com/DefiCake/fuels-rs-65-configurables-issue
To run: `forc build && cargo test`

All transactions to a contract that has been initialized with configurables seem to fail. In the reproduction you can see that I am trying to call a pure function `_proxy_pure_fn` that is supposed to return `255`.

Function definition:
https://github.com/DefiCake/fuels-rs-65-configurables-issue/blob/db85be605137a197d9979dc8b401b35a5839c443/src/main.sw#L103

Call in the tests:
https://github.com/DefiCake/fuels-rs-65-configurables-issue/blob/db85be605137a197d9979dc8b401b35a5839c443/tests/harness.rs#L131

In the test file, there are two functions `test_with_configurables` and `test_without_configurables` whose only difference is:

```rust
let configurables = MyContractConfigurables::default()
            .with_INITIAL_OWNER(State::Initialized(wallet.address().into()))
            .unwrap()
            .with_INITIAL_TARGET(
                ContractId::from_str(
                    "deadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef"
                ).unwrap()
            )
            .unwrap();

// With configurables:
let load_configuration = LoadConfiguration::default().with_configurables(configurables);
// Without configurables:
let load_configuration = LoadConfiguration::default();
```

UPDATE. It seems the issue revolves around 

```rust
.with_INITIAL_TARGET(
    ContractId::from_str(
        "deadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef"
    ).unwrap()
)
```

Removing this specific configurable also makes the test pass

**Comment by hal3e** [comment] 2024-08-19 07:16
fix got merged: https://github.com/FuelLabs/sway/pull/6366
we are waiting for a new `forc` release

**Comment by hal3e** [comment] 2024-08-20 07:38
the issue is resolved. I tested it with:
```
fuel-asm = "0.56.0"
fuel-tx = "0.56.0"
fuel-core-types = { version = "0.32.1", default-features = false }
fuels = { version = "0.66.1", features = ["fuel-core-lib"] }
```
and `forc` `0.63.1`

**Closed** 2024-08-20 14:16 UTC
Labels: bug, blocked
