### ISSUE TITLE
Panic due to `ArithmeticOverflow` is ignored by SDK.

### ISSUE THREAD

**Issue by nfurfaro** [FuelLabs/fuels-rs#307] opened 2022-05-23 11:29 UTC
I have a small script which fails as expected with:
```
[Panic { id: 0000000000000000000000000000000000000000000000000000000000000000, reason: InstructionResult { reason: ArithmeticOverflow, instruction: Instruction { op: 20, ra: 17, rb: 17, rc: 16, rd: 0, imm06: 0, imm12: 1024, imm18: 70656, imm24: 4527104 } }, pc: 10384, is: 10352 }, ScriptResult { result: Panic, gas_used: 66 }]
```
if I run it via forc run  (ie: no SDK involved).

However, if I instead run the script via the sdk and forc test , it passes with:
```
running 1 test
test bug_repro::arithmetic_bug ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 81 filtered out; finished in 0.11s
```
The script:
```
script;

 fn pow(a: u64, b: u64) -> u64 {
        asm(r1: a, r2: b, r3) {
            exp r3 r1 r2;
            r3: u64
        }
    }

fn main() -> bool {
    pow(100, 100) == 0
}

```

For convenience, a working example with a runnable SDK test can be found on the `furnic/sdk-bug-repro` branch.

**Comment by Salka1988** [comment] 2022-05-25 11:09
In order to test this bug in harnes.rs, I wrote the test like this:

```rust
#[tokio::test]
async fn arithmetic_bug() {

    use fuel_core::service::{Config, FuelService};
    use fuel_gql_client::client::FuelClient;
    use fuel_tx::{consts::MAX_GAS_PER_TX, Transaction};
    use fuels::contract::script::Script;
    use std::fs::read;

    let path_to_bin = "tests/test_projects/bug_repro/out/debug/bug_repro.bin";

    let bin = read(path_to_bin);
    let server = FuelService::new_node(Config::local_node()).await.unwrap();
    let client = FuelClient::from(server.bound_address);

    let tx = Transaction::Script {
        gas_price: 0,
        gas_limit: MAX_GAS_PER_TX,
        maturity: 0,
        byte_price: 0,
        receipts_root: Default::default(),
        script: bin.unwrap(), // Here we pass the compiled script into the transaction
        script_data: vec![],
        inputs: vec![],
        outputs: vec![],
        witnesses: vec![vec![].into()],
        metadata: None,
    };

    let script = Script::new(tx);
    let receipts = script.call(&client).await.unwrap();
    let return_val = receipts[0].val().unwrap();

    assert_eq!(1, return_val);
}
```
The result was this: 

``called `Result::unwrap()` on an `Err` value: ContractCallError("ArithmeticOverflow")
thread 'arithmetic_bug' panicked at 'called `Result::unwrap()` on an `Err` value: ContractCallError("ArithmeticOverflow")'``

If this is the way to test, then we can see that panic "ArithmeticOverflow" is not ignored by SDK (I checked other tests from Sway and they were Ok)

**Comment by adlerjohn** [comment] 2022-05-25 15:38
Hm. If it's fixed with a new version of fuel-core then maybe it was a bug in the old version. Could ignore it the issue is no longer evident.

**Closed** 2022-05-29 13:07 UTC
Labels: bug, P: high
