### ISSUE TITLE
Enable storage slots initialization on contract deployment

### ISSUE THREAD

**Issue by luizstacio** [FuelLabs/fuels-rs#254] opened 2022-05-05 10:08 UTC
When deploying a contract, it should be possible to initialize storage slots.

Today storage slots are hardcode empty: https://github.com/FuelLabs/fuels-rs/blob/99a7e1682d7ee341ccaf1356a494b5386b0036ee/packages/fuels-contract/src/contract.rs#L404

This looks related to this: https://github.com/FuelLabs/fuels-rs/issues/87

**Comment by vnepveu** [comment] 2022-06-17 13:56
Closing as duplicate of #86

**Comment by vnepveu** [comment] 2022-06-17 13:56
Closing as duplicate of https://github.com/FuelLabs/fuels-rs/issues/86

**Closed by vnepveu** 2022-06-17 13:56 UTC
Labels: enhancement, P: medium
